### ISSUE TITLE
Add desktop centered styling

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-forum#2]
The current styling is targeting mobile/tablet. We want to have a styling for regular desktops as well.

**Comment by nylira** [comment]
I think it makes sense to have a fullscreen desktop style too. So let's have a user option toggle to switch between 1024px fixed width and fluid.

**Comment by faboweb** [comment]
Peng will get on this next week together with the "light theme".

**Comment by nylira** [comment]
This is done.
