### ISSUE TITLE
Improve signed out usability

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-forum#23]
When a user is signed out, they should still be able to click on the New Comment and New Thread buttons.

Here's how the process should go:

1. Signed out user clicks "new thread" button.
2. Authentication check fails `notifyWarn: You must be signed in first to create a thread.`
3. App saves the current section they're trying to create a thread in (e.g. General, or Economics)
4. App redirects them to sign in or register.
5. Once the user signs in, the app should redirect the user back to the New Thread page of the previously saved section.

And likewise for the new comment button - it should make them sign in and then go back to the correct thread with the comment form open.

**Comment by ethanfrey** [comment]
I was just about to open the same issue.

A button with no action seems like a bug. Redirect to sign in is a good action in this case.
