### ISSUE TITLE
Upvoting my own comment fails

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-forum#46]
![image](https://user-images.githubusercontent.com/172531/31534267-cb0689a6-b028-11e7-96e9-7cdcfa6a443a.png)

We need a better warning when users try to upvote comments while logged out. Something like:

```
title: Upvote Failed
body: Please sign in or make an account to upvote.
```

And then let's redirect them to the signin page, and then back to the thread once they've logged in.

**Comment by faboweb** [comment]
Is this a bug or an enhancement? So: Can you not upvote your comments when signed in? Or is this about the bad warning?

**Comment by nylira** [comment]
Hm I think it's an enhancement. A better warning message would help. Redirecting the user when they click upvote while not signed in is probably worth doing too.
