### ISSUE TITLE
Create a signup/login page

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-forum#48]
This is a prerequesit for #23 #46

**Comment by faboweb** [comment]
First suggestions for a login/signup element: @nylira 

![image](https://user-images.githubusercontent.com/5869273/31549727-589401da-b02f-11e7-896b-ac599b244b27.png)
![image](https://user-images.githubusercontent.com/5869273/31549757-6e82b91e-b02f-11e7-8b78-7dd63153ad36.png)

**Comment by nylira** [comment]
Deprecated by moving auth to the wallet.
